bitacora:
    path:     /
    defaults: { _controller: "JYGRevestimientosBundle:Bitacora:index" }

bitacora_show:
    path:     /{id}/show
    defaults: { _controller: "JYGRevestimientosBundle:Bitacora:show" }



