#rutas de la pagina publicitaria
page_verProducto:
    path:  /productos/{id}
    defaults: { _controller: JYGRevestimientosBundle:Page:verProducto }
    requirements:
        methods:  GET

JYGRevestimientosBundle_inicio:
    path:  /
    defaults: { _controller: JYGRevestimientosBundle:Page:index }
    requirements:
        methods:  GET

JYGRevestimientosBundle_productos:
    path:  /productos
    defaults: { _controller: JYGRevestimientosBundle:Page:productos }
    requirements:
        methods:  GET

JYGRevestimientosBundle_galeria:
    path:  /galeria
    defaults: { _controller: JYGRevestimientosBundle:Page:galeria }
    requirements:
        methods:  GET

JYGRevestimientosBundle_contacto:
    path:  /contacto
    defaults: { _controller: JYGRevestimientosBundle:Page:contacto }
    requirements:
        methods:  GET|POST

JYGRevestimientosBundle_quienessomos:
    path:  /quienessomos
    defaults: { _controller: JYGRevestimientosBundle:Page:quienessomos }

#Estas rutas son para el admin :)
jyg_revestimientos_cliente:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/cliente.yml"
    prefix:   /admin/cliente

jyg_revestimientos_deposito:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/deposito.yml"
    prefix:   /admin/deposito

jyg_revestimientos_item:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/item.yml"
    prefix:   /admin/item

jyg_revestimientos_bitacora:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/bitacora.yml"
    prefix:   /admin/bitacora

jyg_revestimientos_usuario:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/usuario.yml"
    prefix:   /admin/usuario

_administrar_galeria:
    path:     /admin/administrargaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:AdministrarGaleria}

_inicio_sesion:
    path:  /iniciosesion
    defaults: { _controller: JYGRevestimientosBundle:Page:inicioSesion }

_cerrar_sesion:
    path:  /cerrarsesion
    defaults: { _controller: JYGRevestimientosBundle:Page:cerrarSesion }

inicio_admin:
    path:  /admin/sistemainventario
    defaults: { _controller: JYGRevestimientosBundle:Page:inicioAdmin }

jyg_revestimientos_venta:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/venta.yml"
    prefix:   /admin/venta

_nueva_imagen:
    path:     /admin/nuevaimagengaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:NuevaImagen }

_editar_imagen:
    path:     /admin/imagengaleria/editar/{id}
    defaults: { _controller: JYGRevestimientosBundle:Galeria:EditarImagen }
    requirements:
        methods:  GET|POST

_eliminar_imagen:
    path:     /admin/eliminarimagengaleria/{id}
    defaults: { _controller: JYGRevestimientosBundle:Galeria:EliminarImagen }
    requirements:
        methods: GET

_mostrar_galeria:
    path:     /mostrargaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:MostrarGaleria }

_productos_tipo: 
    path:     /productos/tipo/{var}
    defaults: { _controller: JYGRevestimientosBundle:Page:Tipo }

jyg_revestimientos_material:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/material.yml"
    prefix:   /admin/material

pageNotFound:
    path:  /{path}
    defaults: { _controller: JYGRevestimientosBundle:Page:pageNotFound, path: '' }
    requirements:
        path: .*