jyg_revestimientos_venta:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/venta.yml"
    prefix:   /venta

jyg_revestimientos_cliente:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente

jyg_revestimientos_material:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/material.yml"
    prefix:   /material

jyg_revestimientos_deposito:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/deposito.yml"
    prefix:   /deposito

jyg_revestimientos_item:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/item.yml"
    prefix:   /item

jyg_revestimientos_bitacora:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/bitacora.yml"
    prefix:   /bitacora

jyg_revestimientos_usuario:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

JYGRevestimientosBundle_inicio:
    pattern:  /
    defaults: { _controller: JYGRevestimientosBundle:Page:index }
    requirements:
        _method:  GET

JYGRevestimientosBundle_productos:
    pattern:  /productos
    defaults: { _controller: JYGRevestimientosBundle:Page:productos }
    requirements:
        _method:  GET

JYGRevestimientosBundle_galeria:
    pattern:  /galeria
    defaults: { _controller: JYGRevestimientosBundle:Page:galeria }
    requirements:
        _method:  GET

JYGRevestimientosBundle_contacto:
    pattern:  /contacto
    defaults: { _controller: JYGRevestimientosBundle:Page:contacto }
    requirements:
        _method:  GET|POST

JYGRevestimientosBundle_ayuda:
    pattern:  /ayuda
    defaults: { _controller: JYGRevestimientosBundle:Page:ayuda }
    requirements:
        _method:  GET

JYGRevestimientosBundle_mision:
    pattern:  /mision
    defaults: { _controller: JYGRevestimientosBundle:Page:mision }
    requirements:
        _method:  GET

JYGRevestimientosBundle_vision:
    pattern:  /vision
    defaults: { _controller: JYGRevestimientosBundle:Page:vision }
    requirements:
        _method:  GET