jyg_revestimientos_cliente:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente

jyg_revestimientos_deposito:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/deposito.yml"
    prefix:   /deposito

jyg_revestimientos_item:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/item.yml"
    prefix:   /item

jyg_revestimientos_bitacora:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/bitacora.yml"
    prefix:   /bitacora

jyg_revestimientos_usuario:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

page_verProducto:
    pattern:  /productos/{id}
    defaults: { _controller: JYGRevestimientosBundle:Page:verProducto }
    requirements:
        _method:  GET

JYGRevestimientosBundle_inicio:
    pattern:  /
    defaults: { _controller: JYGRevestimientosBundle:Page:index }
    requirements:
        _method:  GET

JYGRevestimientosBundle_productos:
    pattern:  /productos
    defaults: { _controller: JYGRevestimientosBundle:Page:productos }
    requirements:
        _method:  GET

JYGRevestimientosBundle_galeria:
    pattern:  /galeria
    defaults: { _controller: JYGRevestimientosBundle:Page:galeria }
    requirements:
        _method:  GET

JYGRevestimientosBundle_contacto:
    pattern:  /contacto
    defaults: { _controller: JYGRevestimientosBundle:Page:contacto }
    requirements:
        _method:  GET|POST

JYGRevestimientosBundle_quienessomos:
    pattern:  /quienessomos
    defaults: { _controller: JYGRevestimientosBundle:Page:quienessomos }

jyg_revestimientos_venta:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/venta.yml"
    prefix:   /venta

#Estas rutas son para el admin :)
_administrar_geleria:
    path:     /administrargaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:AdministrarGaleria}

#Hecha
_nueva_imagen:
    path:     /nuevaimagengaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:NuevaImagen }

_editar_imagen:
    path:     /editarimagengaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:EditarImagen }

_eliminar_imagen:
    path:     /eliminarimagengaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:EliminarImagen }

_mostrar_galeria:
    path:     /mostrargaleria
    defaults: { _controller: JYGRevestimientosBundle:Galeria:MostrarGaleria }

jyg_revestimientos_material:
    resource: "@JYGRevestimientosBundle/Resources/config/routing/material.yml"
    prefix:   /material